import Head from 'next/head'
import Link from 'next/link'
import { ChangeEventHandler, useEffect, useState } from 'react'
import { trpc } from '../helpers/trpc'
import styles from '../styles/Home.module.css'

export default function Home() {
    const [text, setText] = useState('')
    const { data, hasNextPage, fetchNextPage, isFetchingNextPage } = trpc.useInfiniteQuery(
        ['getAllCountries', { name: text }],
        {
            getNextPageParam: (lastCursor) => lastCursor.nextCursor
        }
    )

    const handleLoadMore = async () => {
        await fetchNextPage()
    }

    const handleChange: ChangeEventHandler<HTMLInputElement> = (e) => {
        setText(e.target.value)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <input type="text" placeholder="Search..." onChange={handleChange} />

            {data?.pages
                .reduce((acc, page) => {
                    page.countries.forEach((country) => {
                        acc.push(country)
                    })

                    return acc
                }, [])
                .map((country) => (
                    <div key={country.name}>
                        <Link href={`/${country.name}`}>
                            <a>
                                <p>{country.name}</p>
                            </a>
                        </Link>
                    </div>
                ))}

            <div>
                <button disabled={!hasNextPage || isFetchingNextPage} onClick={handleLoadMore}>
                    Load more
                </button>
            </div>
        </div>
    )
}
