import Head from 'next/head'
import { trpc } from '../helpers/trpc'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { data: countries } = trpc.useQuery(['getAllCountries'])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input type="text" placeholder='Search...' />

      {countries?.map(country => (

        <div key={country.name}>
          <p>{country.name}</p>
        </div>
      ))}
    </div>
  )
}
